name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for adding your first issue and taking time to make AST better.'
        pr-message: 'Thanks for issuing your first pull request and actively collaborating.'
