# This is a basic workflow to help you get started with Actions

name: CI

defaults:
  run:
    shell: bash

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.1.0
      with:
        required-ros-distributions: noetic
    - uses: ros-tooling/action-ros-ci@0.1.0
      with:
        package-name: ast_ros
        target-ros1-distro: noetic
        vcs-repo-file-url: ""
        import-token: ${{ secrets.mega }}
